spring:
    application:
        name: Telegram-Service
    rabbitmq:
        host: rabbitmq
        port: 5672
        username: root
        password: admin
bot:
    name: "InvestmentNotificationBot"
    token: "7402051299:AAGEWx6JEhpGIGC4tVLjIXL7hW2gE36Gkb0"
scheduling:
    fixed-rate: 300000