spring:
    application:
        name: Investment-Service
    rabbitmq:
        host: rabbitmq
        port: 5672
        username: root
        password: admin
tinkoff:
    token: "t.ybG0mUyoNhrEspFYO4lQ-iwyUgG5QH7zpvYInkWkPyPglA9LtAo_RbX7l7wFRpTM45Kax-mLgu-pQZ5I39KB5A"